### ISSUE TITLE
lasso-select and range-select  not showing the select outline on mode: markers

### ISSUE THREAD

**Issue by jorrog** [plotly/angular-plotly.js#39] opened 2019-01-30 13:36 UTC
Using ver. 1.0.1 the lasso-select and range-select  not showing the select outline on mode: markers.
When the mode is Lines everything works as expected.

**Comment by andrefarzat** [comment] 2019-02-03 23:44
@jorrog what module are you using? `PlotlyModule`, [`PlotlyViaCDNModule`](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module) or [`PlotlyViaWindowModule`](https://github.com/plotly/angular-plotly.js#plotly-via-window-module) ?
This question is important, for I am afraid that angular's minifier screws up `plotly.js` code

**Comment by andrefarzat** [comment] 2019-02-04 10:50
@jorrog please, test with other module ( [`PlotlyViaCDNModule`](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module) for example) and let us know if the issue persists

**Comment by jorrog** [comment] 2019-02-11 08:44
@andrefarzat same thing. When i have only line plots the selection is working fine, but when I put the scatter mode the selection outline is gone.

**Comment by andrefarzat** [comment] 2019-09-01 02:28
Looks like the issue is not happening. I dunno if it was in `plotly.js` itself. I will close this issue. Please reopen if you're still seeing the issue

**Closed by andrefarzat** 2019-09-01 02:28 UTC
Labels: bug
